{
    'name': 'SHIFA Management',
    'version': '1.0.0',
    'summary': 'Membership, Dependents, Medical Assistance & Website form for SHIFA',
    'author': 'Zafir Sk Heerah',
    'category': 'Membership',
    'depends': [
        'base',
        'contacts',
        'account',
        'account_payment',
        'website'
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/payment_journals.xml',
        'data/account_journal_data.xml',
        'report/report.xml',
        'views/shifa_member_views.xml',
        'views/shifa_dependent_views.xml',
        'views/shifa_medical_views.xml',
        'views/shifa_committee_views.xml',
        'views/shifa_reporting_views.xml',
        'views/shifa_config_views.xml',
        'views/shifa_menu.xml',
        'views/shifa_membership_application_form.xml',
        'views/shifa_membership_application_form_pdf.xml',
        'views/account_payment_register_views.xml',
        'data/email_templates.xml',
        'data/cron_jobs.xml',
        'data/report_url_param.xml',
    ],
    'application': True,
    'installable': True,
}
